services:
  - type: web
    name: narveka-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations store && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: narveka-db
          property: connectionString
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  - name: narveka-db
    databaseName: narveka
    user: narveka
